### ISSUE TITLE
unimplemented commands

### ISSUE THREAD

**Issue by sxyizhiren** [wilkenstein/redis-mock-js#1]
hi my code need to call below redis command:
zinterstore,zunionstore,zrevrange,zremrangebyrank

will you implement them later?

**Comment by wilkenstein** [comment]
Hi!

Yes. I'm planning on implementing them over the course of the next week. My goal is to have all set & sorted set commands implemented by 3/16.

**Comment by sxyizhiren** [comment]
OK.good news for me

**Comment by wilkenstein** [comment]
68f94f8ee0404bb75fed0167ac4e7689eeca2de3, release 0.0.9-4 has support for all zset commands, but I haven't tested them fully, so no guarantee that they all work! Going to test them throughout this week, then 0.0.10 will have the tested zset commands.

**Comment by sxyizhiren** [comment]
great! i will use it !
