### ISSUE TITLE
multi cmd invalid

### ISSUE THREAD

**Issue by sxyizhiren** [wilkenstein/redis-mock-js#2]
hi, i found the multi command invalid, could you also check it?
i call the multi with some "zadd", but in fact, zadd was not called.  

  console.log('cmds:',cmds);
  db.multi(cmds).exec(noop);

//print
cmds: [ [ 'zadd', 'reds:word:KBRT', 1, 6 ],
  [ 'zadd', 'reds:object:6', 1, 'KBRT' ],
  [ 'zadd', 'reds:word:KT', 1, 6 ],
  [ 'zadd', 'reds:object:6', 1, 'KT' ] ]

**Comment by wilkenstein** [comment]
Fixed in 0.0.12.
