### ISSUE TITLE
Feature Request: .flushAll()

### ISSUE THREAD

**Issue by jpodwys** [wilkenstein/redis-mock-js#9]
I would really appreciate `.flushAll()` being implemented. Thanks for the great work!

**Comment by wilkenstein** [comment]
Hi @jpodwys, thanks! I've been on vacation, but I will implement flushAll Wednesday and get a point release out. It'll just do flushdb right now....

**Comment by jpodwys** [comment]
Sounds, awesome! Thanks!

**Comment by jpodwys** [comment]
@wilkenstein I'm hoping to push out a 1.0.0 release for one of my repos today and I wanted to upgrade to redis-js as part of that release. Do you have a new ETA for `.flushAll()`? Thanks for your help!

**Comment by jpodwys** [comment]
Just to clarify, I'm happy to push my release off if you're able to make time to add `.flushAll()` within a couple of days. Otherwise it will just have to be a post-1.0.0 enhancement.

**Comment by wilkenstein** [comment]
Sorry, yesterday was crazy. Done in 0.0.12-5.

**Comment by jpodwys** [comment]
Thank you!
